// I will not be including any HDCP keys or anything like that in this file or helping anyone break HDCP, you will need to find them yourself
// this is simply a reverse engineering of the HDCP functions in the HV
// and by "reverse-engineering" I mean "copy-paste from Ghidra's decomp" since these functions are all extremely simple, just math operations and bit shifting

// all functions seem to take the same set of arguments for r4 and r5
// r4 - unknown
// r5 - "An" - random seed generated by transmitter (xbox)

// 17559 RETAIL
// Address: 00029648
// ------------------------------------------
// calculates the HDCP Mi (?)
// m0 - initialisation value sent from reciever
unsigned long long HdcpCalculateMi(unsigned long long m0, unsigned long long r4, unsigned long long an)
{
    unsigned long long offset = 0x0000000200000000ULL;
    return *(unsigned long long *)(0x00016AC0 + offset) ^ m0 ^ r4 ^ an;
}

// 17559 RETAIL
// Address: 00023698
// ------------------------------------------
// calculates the HDCP AKsv signature (transmitter Ksv)
unsigned long long HdcpCalculateAKsvSignature(unsigned long long aksv, unsigned long long r4, unsigned long long an)
{
    return (aksv >> 0x11 & 0x80 | aksv >> 0x19 & 0x7f) +
                   (aksv >> 0x25 & 7 | aksv >> 0x1d & 0xf8) +
                   (aksv >> 0x16 & 3 | aksv >> 0xe & 0xfc) +
                   (aksv >> 0xb & 0x1f | aksv >> 3 & 0xe0) + (aksv >> 7 & 1 | (aksv & 0x7f) << 1) &
               0xff ^
           r4 & 0xff ^ an & 0xff ^ 0x3a;
}

// 17559 RETAIL
// Address: 00023718
// ------------------------------------------
// calculates the HDCP BKsv signature (receiver Ksv)
unsigned long long HdcpCalculateBKsvSignature(unsigned long long bksv, unsigned long long r4, unsigned long long an)
{
    return (bksv >> 0x27 & 1 | bksv >> 0x1f & 0xfe) +
                   (bksv >> 0x1b & 0x1f | bksv >> 0x13 & 0xe0) +
                   (bksv >> 10 & 0x3f | bksv >> 2 & 0xc0) +
                   (bksv >> 0x14 & 0xf | bksv >> 0xc & 0xf0) + (bksv & 0xff) &
               0xff ^
           r4 >> 8 & 0xff ^ an >> 8 & 0xff ^ 0x72;
}